"""content_engine_schema

Revision ID: 20723ace4ccf
Revises: 0000
Create Date: 2026-09-30 19:43:06.049443
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20723ace4ccf"
down_revision: str | Sequence[str] | None = "0000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "dead",
                name="jobstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index("ix_jobs_state_run_after", "jobs", ["state", "run_after"], unique=False)
    op.create_table(
        "lessons",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposed_by", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "proposed", "active", "retired", name="lessonstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("eval_run_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "news_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum(
                "normal",
                "important",
                "high",
                "breaking",
                name="newstier",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corroboration_count", sa.Integer(), nullable=False),
        sa.Column("primary_url", sa.Text(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "analyzed",
                "decomposed",
                "generated",
                "validated",
                "queued",
                "scheduled",
                "published",
                "measured",
                "archived",
                "recyclable",
                "rejected",
                "skipped",
                name="lifecycle",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent", "version"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("pipeline", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running", "succeeded", "failed", name="runstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("tokens_in", sa.BigInteger(), nullable=False),
        sa.Column("tokens_out", sa.BigInteger(), nullable=False),
        sa.Column("langfuse_trace_id", sa.String(length=128), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_pipeline"), "runs", ["pipeline"], unique=False)
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("github_repo", "news_feed", name="sourcekind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("credibility", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active", "paused", "excluded", name="sourcestatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("last_scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_commit_sha", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "topic_history",
        sa.Column("topic_key", sa.String(length=200), nullable=False),
        sa.Column("last_published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cooldown_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("topic_key"),
    )
    op.create_table(
        "knowledge_nodes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("repo", "chapter", "concept", name="nodekind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("doc_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["knowledge_nodes.id"],
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "news_items",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["news_events.id"],
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(
        op.f("ix_news_items_content_hash"), "news_items", ["content_hash"], unique=False
    )
    op.create_table(
        "source_documents",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("blob_sha", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "path"),
    )
    op.create_table(
        "opportunities",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("knowledge_node_id", sa.BigInteger(), nullable=True),
        sa.Column("news_event_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "pillar",
            sa.Enum(
                "building_ai_systems",
                "ai_in_production",
                "ai_news_practitioner",
                "ai_enablement",
                "teaching_ai",
                name="pillar",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("angle", sa.Text(), nullable=False),
        sa.Column(
            "format",
            sa.Enum(
                "text",
                "carousel",
                "thread",
                "article",
                name="contentformat",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("audience", sa.Text(), nullable=True),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("series_key", sa.String(length=128), nullable=True),
        sa.Column("priority", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "analyzed",
                "decomposed",
                "generated",
                "validated",
                "queued",
                "scheduled",
                "published",
                "measured",
                "archived",
                "recyclable",
                "rejected",
                "skipped",
                name="lifecycle",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_node_id"],
            ["knowledge_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["news_event_id"],
            ["news_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_opportunities_status"), "opportunities", ["status"], unique=False)
    op.create_table(
        "drafts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("hook_type", sa.String(length=64), nullable=True),
        sa.Column(
            "format",
            sa.Enum(
                "text",
                "carousel",
                "thread",
                "article",
                name="contentformat",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("prompt_version_id", sa.BigInteger(), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("langfuse_trace_id", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "analyzed",
                "decomposed",
                "generated",
                "validated",
                "queued",
                "scheduled",
                "published",
                "measured",
                "archived",
                "recyclable",
                "rejected",
                "skipped",
                name="lifecycle",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opportunity_id", "version"),
    )
    op.create_table(
        "channel_variants",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("draft_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "linkedin",
                "x",
                "bluesky",
                "threads",
                "instagram",
                "facebook",
                "whatsapp",
                "slack",
                "telegram",
                "discord",
                "blog",
                "devto",
                "hashnode",
                "newsletter",
                name="channel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("media", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "analyzed",
                "decomposed",
                "generated",
                "validated",
                "queued",
                "scheduled",
                "published",
                "measured",
                "archived",
                "recyclable",
                "rejected",
                "skipped",
                name="lifecycle",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["draft_id"], ["drafts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "channel"),
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("draft_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "claim_type",
            sa.Enum(
                "confirmed",
                "announced",
                "reported",
                "speculation",
                name="claimtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("evidence_url", sa.Text(), nullable=True),
        sa.Column("evidence_span", sa.Text(), nullable=True),
        sa.Column(
            "verdict",
            sa.Enum(
                "supported",
                "unsupported",
                "speculation_labelled",
                name="claimverdict",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["draft_id"], ["drafts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quality_reports",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("draft_id", sa.BigInteger(), nullable=False),
        sa.Column("variant_id", sa.BigInteger(), nullable=True),
        sa.Column("rubric", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("overall", sa.Float(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("judge_model", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["draft_id"], ["drafts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["channel_variants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule_slots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "linkedin",
                "x",
                "bluesky",
                "threads",
                "instagram",
                "facebook",
                "whatsapp",
                "slack",
                "telegram",
                "discord",
                "blog",
                "devto",
                "hashnode",
                "newsletter",
                name="channel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "morning",
                "evening",
                "breaking",
                "extra",
                name="slotkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("variant_id", sa.BigInteger(), nullable=True),
        sa.Column("replaced_variant_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "open",
                "filled",
                "published",
                "skipped",
                "cancelled",
                name="slotstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("skip_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["replaced_variant_id"],
            ["channel_variants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["channel_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "scheduled_for"),
    )
    op.create_index(
        op.f("ix_schedule_slots_scheduled_for"), "schedule_slots", ["scheduled_for"], unique=False
    )
    op.create_table(
        "publications",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("slot_id", sa.BigInteger(), nullable=False),
        sa.Column("variant_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "linkedin",
                "x",
                "bluesky",
                "threads",
                "instagram",
                "facebook",
                "whatsapp",
                "slack",
                "telegram",
                "discord",
                "blog",
                "devto",
                "hashnode",
                "newsletter",
                name="channel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum(
                "shadow", "veto", "autonomous", name="publishmode", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "published",
                "failed",
                "deleted",
                name="publicationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["schedule_slots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["channel_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "metrics_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("publication_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "taken_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "source",
            sa.Enum("api", "csv", name="metricssource", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("members_reached", sa.Integer(), nullable=True),
        sa.Column("reactions", sa.Integer(), nullable=True),
        sa.Column("comments", sa.Integer(), nullable=True),
        sa.Column("reshares", sa.Integer(), nullable=True),
        sa.Column("saves", sa.Integer(), nullable=True),
        sa.Column("sends", sa.Integer(), nullable=True),
        sa.Column("link_clicks", sa.Integer(), nullable=True),
        sa.Column("followers_gained", sa.Integer(), nullable=True),
        sa.Column("profile_views", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["publication_id"], ["publications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metrics_snapshots_publication_id"),
        "metrics_snapshots",
        ["publication_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metrics_snapshots_publication_id"), table_name="metrics_snapshots")
    op.drop_table("metrics_snapshots")
    op.drop_table("publications")
    op.drop_index(op.f("ix_schedule_slots_scheduled_for"), table_name="schedule_slots")
    op.drop_table("schedule_slots")
    op.drop_table("quality_reports")
    op.drop_table("claims")
    op.drop_table("channel_variants")
    op.drop_table("drafts")
    op.drop_index(op.f("ix_opportunities_status"), table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_table("source_documents")
    op.drop_index(op.f("ix_news_items_content_hash"), table_name="news_items")
    op.drop_table("news_items")
    op.drop_table("knowledge_nodes")
    op.drop_table("topic_history")
    op.drop_table("sources")
    op.drop_table("settings")
    op.drop_index(op.f("ix_runs_pipeline"), table_name="runs")
    op.drop_table("runs")
    op.drop_table("prompt_versions")
    op.drop_table("news_events")
    op.drop_table("lessons")
    op.drop_index("ix_jobs_state_run_after", table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
